### ISSUE TITLE
`Multi` worker undersaturated

### ISSUE THREAD

**Issue by dlecocq** [seomoz/qless-js#18]
We encountered a bug whereby the worker will fail to keep itself fully saturated under certain conditions, notably when using `max-concurrency`.

Then the `multi` worker is run, it begins by acquiring the semaphore, popping a job, running it, and so forth. The problem comes from the fact that the `popper` assumes that the only reason that a job would be unavailable is because there are no jobs in the queue(s) it's targeting. As a result, in that instance, it waits some provided interval. The other condition under which it might not be able to pop a job is if `max-concurrency` is met, which is a condition that might change as soon as a job completes.

We observe this as a pattern of spikey 'running jobs' counts. The jobs complete in under the `popper` wait interval:

<img width="540" alt="screen shot 2017-11-01 at 8 47 46 am" src="https://user-images.githubusercontent.com/952157/32292699-2218cc48-befe-11e7-8bb4-c24a80949b9b.png">

We're working on a fix and hope to have a PR out shortly.

**Comment by b4hand** [comment]
I haven't looked at the PR yet, but hopefully, you don't just plan to poll more all the time. Is your plan to distinguish between the two different modes?

**Comment by dlecocq** [comment]
Closed with #19 . Here you can see the undersaturation of one of our workers before this fix, and then the full saturation of it after the fix was deployed.

<img width="562" alt="screen shot 2017-11-04 at 7 41 22 am" src="https://user-images.githubusercontent.com/952157/32406336-cf82e5bc-c133-11e7-9f6f-357e3bdf64ad.png">
