### ISSUE TITLE
Retry transient errors?

### ISSUE THREAD

**Issue by dlecocq** [seomoz/qless-js#20]
We occasionally run into transient network errors, including when talking to redis through `qless`. I personally have mixed feelings about clients that automatically retry things on my behalf; in most cases one can implement the appropriate retry logic on their own rather than rely on the library doing it. However, there are some instances where it would be difficult or impossible to reach through the client code to adjust the retries (for instance in `job`, where it `catch`es failed job execution and then calls `job.fail` -- our code couldn't reach through that to add retries around the call to `job.fail`).

So I figured I'd ask y'all to see what you think about it.

**Comment by b4hand** [comment]
I think retries for known idempotent operations are reasonable, but for operations that are not known to be idempotent, we should be very careful.

**Comment by dlecocq** [comment]
Turns out `node_redis` uses a notion of a `retry_strategy`, which can be configured at client creation time. Since we pass in our client's config directly to `node_redis`'s, users can already get the retry logic they want.
