### ISSUE TITLE
Latest PRs obscure errors

### ISSUE THREAD

**Issue by evanbattaglia** [seomoz/qless-js#26]
@b4hand @dlecocq 

I was trying to use qless-js as a npm module in github (i.e., adding `"qless-js": "git+https://github.com/seomoz/qless-js.git"` in my `package.json` dependencies). It didn't work because it didn't have the qless-core lua scripts -- these are checked out and built in the `prepublish` script. This is fine, but it took me a while to determine that this was the problem. Unfortunately it seems like the past couple PRs have reduced visibility into errors.

In v0.2.1 (after #24) the error I get is this:

```
$ node_modules/.bin/qless-js-worker -q foo
Thu Jan 18 2018 12:23:05 GMT‌-0800 (PST) | PID 30567 | ERROR | Worker 2 died...
Thu Jan 18 2018 12:23:05 GMT‌-0800 (PST) | PID 30567 | ERROR | Worker 0 died...
Thu Jan 18 2018 12:23:05 GMT‌-0800 (PST) | PID 30567 | ERROR | Worker 2 died...
Thu Jan 18 2018 12:23:05 GMT‌-0800 (PST) | PID 30567 | ERROR | Worker 2 died...
Thu Jan 18 2018 12:23:05 GMT‌-0800 (PST) | PID 30567 | ERROR | Worker 2 died...
Thu Jan 18 2018 12:23:05 GMT‌-0800 (PST) | PID 30567 | ERROR | Worker 0 died...
```

in v0.2.0 (after #23)
```
$ node_modules/.bin/qless-js-worker -q foo
undefined
Unhandled rejection Error
```

Only in v0.1.5 is it clear what the problem is:
```
$ node_modules/.bin/qless-js-worker -q foo undefined
Unhandled rejection
Error: ENOENT: no such file or directory, open '/home/evan/dev/myproject/node_modules/qless-js/lib/qless-core/qless.lua'
```

Is there any way to get back the same level of visibility that we had before?

**Comment by dlecocq** [comment]
That's interesting. I'm not sure off hand why that would happen, but I can look into it.
